version: '3'

services:
  cli:
    image: mcr.microsoft.com/azure-cli:latest
    command: sleep 86400
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${http_proxy}
    volumes:
      - ./:/terraform