version: '3'

services:
  cli:
    image: mud5150/addtoaz:latest
    command: sleep 86400
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${http_proxy}
    volumes:
      - ./:/terraform